sudo: enabled
dist: bionic
language: python
os:
  - linux
python:
  - "3.8"
services:
  - mongodb

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python-pip libssl-dev

install:
  - pip install -r requirements.txt
  - pip install pytest

jobs:
  include:
    - stage: "API Tests"
      name: "PyTest Tests"
      before_script:
        - sleep 15
        - bash ./scripts/setup_mongo.sh
      script:
        - pytest -vv