sudo: enabled
services: docker
dist: bionic
language: python
os:
  - linux
python:
  - "3.8"
env:
 - DB_URI=${DB_URI}

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python-pip libssl-dev

install:
  - pip install -r requirements.txt
  - pip install pytest

jobs:
  include:
    - stage: "API Tests"
      name: "PyTest Tests"
      script:
        - pytest -vv